-- MySQL Script generated by MySQL Workbench
-- Tue Feb 22 16:25:51 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Rodzinki
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Rodzinki
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Rodzinki` DEFAULT CHARACTER SET utf8 ;
USE `Rodzinki` ;

-- -----------------------------------------------------
-- Table `Rodzinki`.`Rodzina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Rodzinki`.`Rodzina` (
  `ID` INT UNSIGNED NULL AUTO_INCREMENT,
  `Nazwa` VARCHAR(255) NOT NULL,
  `Niemowleta` INT NOT NULL,
  `Dzieci` INT NOT NULL,
  `Dorosli` INT NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `idtable1_UNIQUE` (`ID` ASC) VISIBLE,
  UNIQUE INDEX `Nazwa_UNIQUE` (`Nazwa` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Rodzinki`.`Czlonkowie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Rodzinki`.`Czlonkowie` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Imie` VARCHAR(255) NOT NULL,
  `Nazwa Rodziny` VARCHAR(255) NOT NULL,
  `Wiek` INT NOT NULL,
  PRIMARY KEY (`id`, `Nazwa Rodziny`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
